[build]
  publish = "."                       # Folder where your index.html is
  functions = "netlify/functions"    # Folder containing your serverless functions

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
